[versions]
# kotlin
kotlin = "2.2.20"

# plugin
googleService = "4.4.4"

# agp
agp = "8.13.0"

# ksp
ksp = "2.1.20-2.0.0"

# jvm
jetbrainsKotlinJvm = "2.2.20"

# jetpack
coreKtx = "1.17.0"
androidxLifecycle = "2.9.4"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
material = "1.13.0"
activity = "1.11.0"
jetpack-fragment = "1.8.9"
datastore = "1.1.7"
room = "2.8.2"
workManager = "2.10.5"
splash = "1.0.1"
startup = "1.2.0"
exoPlayer = "1.8.0"
pagingTesting = "3.3.6"
material3-icons = "1.7.8"

# compose
composeBom = "2025.10.00"
activityCompose = "1.11.0"
compose-compiler = "1.4.5"
compose-navigation = "2.9.5"
compose-hilt-navigation = "1.3.0"
compose-paging = "3.3.6"
androidxNavigation = "2.8.4"
constraintLayout = "1.1.1"

#junit
junit = "4.13.2"
junitVersion = "1.3.0"

# Coroutine
kotlinxCoroutines = "1.10.2"

# espresso
espressoCore = "3.7.0"

# hilt
hilt = "2.57.2"
hiltExt = "1.3.0"

# retrofit2
mockwebserver = "5.2.1"
retrofit2 = "3.0.0"

# okhttp
okhttp-okHttp = "5.2.1"
okhttp-profiler = "1.0.8"

# kotlin serialization
serialization-kotlin = "1.9.0"
serialization-converter = "1.0.0"

# coil
coil = "3.3.0"

# firebase
firebaseBom = "33.16.0"
firebaseCrashlyticsPlugin = "3.0.4"
firebasePerfPlugin = "1.4.2"

# test
androidxTestRules = "1.7.0"
androidxTestCore = "1.7.0"
androidxTestRunner = "1.7.0"

# robolectric
robolectric = "4.16"

# turbin
turbine = "1.2.1"

# threentenabp
threentenabp = "1.4.9"

# youtube player
youtubePlayer = "13.0.0"

# lottie
lottieCompose = "6.6.10"

[libraries]
# gradle plugin
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
android-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

# kotlin
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlin" }

# jetpack
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
#androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntime" }
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "jetpack-fragment" }
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore"}
androidx-dataStore-core = { group = "androidx.datastore", name = "datastore-core", version.ref = "datastore" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-work-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }
androidx-splash = { group = "androidx.core", name = "core-splashscreen", version.ref = "splash" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "startup" }
androidx-media3-exoplayer = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "exoPlayer" }
androidx-media3-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "exoPlayer" }
androidx-paging-testing = { group = "androidx.paging", name = "paging-testing", version.ref = "pagingTesting" }

# compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-hilt-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "compose-hilt-navigation" }
androidx-compose-paging = { group = "androidx.paging", name = "paging-compose", version.ref = "compose-paging" }
androidx-paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "compose-paging" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtimeTesting = { group = "androidx.lifecycle", name = "lifecycle-runtime-testing", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "compose-navigation" }
androidx-compose-material3-navigationSuite = { group = "androidx.compose.material3", name = "material3-adaptive-navigation-suite" }
androidx-compose-constraintLayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintLayout"}

# material
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive" }
androidx-compose-material3-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material3-icons" }

# junit
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }

# Coroutine
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }

# espresso
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
hilt-ext-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltExt" }

# kotlin serialization
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization-kotlin" }
kotlinx-serialization-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "serialization-converter" }

# retrofit2
mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "mockwebserver" }
retrofit2 = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit2" }

# okhttp
okhttp-bom = { group = "com.squareup.okhttp3", name = "okhttp-bom", version.ref = "okhttp-okHttp" }
okhttp-okhttp = { group = "com.squareup.okhttp3", name = "okhttp" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor" }
okhttp-profiler = { group = "com.localebro", name = "okhttpprofiler", version.ref = "okhttp-profiler" }

# coil
coil = { group = "io.coil-kt.coil3", name = "coil", version.ref = "coil" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
coil-core = { group = "io.coil-kt.coil3", name = "coil-core", version.ref = "coil" }

# firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-performance = { group = "com.google.firebase", name = "firebase-perf-ktx" }
firebase-message = { group = "com.google.firebase", name = "firebase-messaging-ktx" }
firebase-crashlytics-gradlePlugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "firebaseCrashlyticsPlugin" }
firebase-performance-gradlePlugin = { group = "com.google.firebase", name = "perf-plugin", version.ref = "firebasePerfPlugin" }

# test
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }

# robolectric
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }

# turbin
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine" }

# threentenabp
threetenabp = { group = "com.jakewharton.threetenabp", name = "threetenabp", version.ref = "threentenabp" }

# youtube player
youtube-player = { group = "com.pierfrancescosoffritti.androidyoutubeplayer", name = "core", version.ref = "youtubePlayer" }

# Inject
javax-inject = { group = "javax.inject", name = "javax.inject", version = "1" }

# lottie
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottieCompose" }

# plugin
ksp-gradlePlugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
room-gradlePlugin = { group = "androidx.room", name = "room-gradle-plugin", version.ref = "room" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-service = { id = "com.google.gms.google-services", version.ref = "googleService" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPlugin" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerfPlugin" }
room = { id = "androidx.room", version.ref = "room" }

# Plugins defined by this project
bowoon-android-application = { id = "bowoon.android.application" }
bowoon-android-application-compose = { id = "bowoon.android.application.compose" }
bowoon-android-application-firebase = { id = "bowoon.android.application.firebase" }
bowoon-android-application-flavors = { id = "bowoon.android.application.flavors" }
bowoon-android-feature = { id = "bowoon.android.feature" }
bowoon-android-library = { id = "bowoon.android.library" }
bowoon-android-library-compose = { id = "bowoon.android.library.compose" }
bowoon-android-room = { id = "bowoon.android.room" }
bowoon-hilt = { id = "bowoon.hilt" }
bowoon-jvm-library = { id = "bowoon.jvm.library" }